knp_paginator:
    page_range: 5 # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
